### PR TITLE
Move gogs admin user creation into its own errand

### PR DESCRIPTION
**Pull request by shreddedbacon**
When I went to use this bosh release, I found the admin user was not being created. #20 mentions this too
This moves the creation of the admin account out of `gogs_ctl` and into its own errand.

I will also have follow up PR coming which adds the ability to specify authentication backends (LDAP, SMTP) which means this account creation can be optional.

### CODE REVIEW

**Comment by drnic** [comment]
Sorry I haven't gotten to this PR yet. I'll try to look at it next week (and fix up CI).

**Comment by drnic** [comment]
@shreddedbacon good news - I've fixed the CI and upgraded the base stemcell.

Unfortunately for you -- I need you to rebase your PR against master so that CI can get the updated CI scripts from your branch. Possible for you to do this? I know you submitted the PR a long time ago. I'm sorry.

**Comment by drnic** [comment]
Thanks @shreddedbacon 

If we're lucky enough to get more PRs from you in future, create a `ci/release_notes.md` (if missing) for the text you want to go out into the Github Release notes. Don't worry about it now, I'll create it for the next release.

**Comment by drnic** [comment]
Want me to hold off on next gogs release until you're next PR?

**Comment by shreddedbacon** [comment]
Yes please, I will work on the next PR over the next few days.

**Pull request merged**
